-- 396: crm_calc_participation учитывает room_number_pattern — тариф выбирается
-- по номеру комнаты при равной вместимости. Применена через MCP 16.08.2026.
-- Проверено: Girigaj View → 1250 ₹/ночь, Delux → 1000 ₹/ночь (rollback-тест).
