-- Переводы накладных расходов на экране «Кухня → Себестоимость» (см. 492)
insert into translations (key, ru, en, hi, context) values
('cost_subtitle', 'Продукты по рецептам, посуда, готовое со стороны, плюс накладные: зарплаты, общие расходы и расходы «на ретрит». Всё делится на фактических вкушающих.', 'Ingredients by recipes, tableware, ready-made food, plus overhead: salaries, general expenses and per-retreat expenses. Everything is divided among actual diners.', 'व्यंजनों के अनुसार सामग्री, बर्तन, बाहर से तैयार भोजन, साथ में ओवरहेड: वेतन, सामान्य खर्च और रिट्रीट के खर्च। सब कुछ वास्तविक भोजन करने वालों में बाँटा जाता है।', 'Кухня → Себестоимость'),
('cost_overhead_retreat', 'На ретрит', 'Per retreat', 'रिट्रीट पर', 'Кухня → Себестоимость'),
('cost_overhead_general', 'Общие', 'General', 'सामान्य', 'Кухня → Себестоимость'),
('cost_provisional', 'предв.', 'prelim.', 'प्रारंभिक', 'Кухня → Себестоимость'),
('cost_provisional_hint', 'Период расходов ещё не закончился или зарплата взята оценкой', 'The expense period is not over yet or the salary is an estimate', 'खर्च की अवधि अभी समाप्त नहीं हुई या वेतन अनुमान से लिया गया है', 'Кухня → Себестоимость'),
('cost_overhead_unallocated', 'Накладные расходы без вкушающих или без приёма пищи в меню (не распределены)', 'Overhead with no diners or no meal in the menu (not allocated)', 'बिना भोजन करने वालों या मेनू में भोजन के ओवरहेड खर्च (वितरित नहीं)', 'Кухня → Себестоимость'),
('cost_w_ov_error', 'Не удалось загрузить накладные расходы (зарплаты, общие расходы, билеты), показаны только прямые затраты', 'Could not load overhead (salaries, general expenses, tickets); only direct costs are shown', 'ओवरहेड (वेतन, सामान्य खर्च, टिकट) लोड नहीं हुआ, केवल प्रत्यक्ष लागत दिखाई गई है', 'Кухня → Себестоимость'),
('cost_w_payroll_est', 'Зарплата за месяц взята оценкой (начисления ещё нет), итог предварительный', 'The month''s salary is an estimate (no accrual yet), the total is preliminary', 'महीने का वेतन अनुमान से लिया गया है (अभी कोई प्रोद्भवन नहीं), कुल अनंतिम है', 'Кухня → Себестоимость'),
('cost_w_ov_nobase', 'Расход «на ретрит», а вкушающих ретрита в периоде нет: учтён в общих', 'A per-retreat expense but no retreat diners in the period: counted as general', 'रिट्रीट का खर्च, पर अवधि में रिट्रीट के भोजन करने वाले नहीं: सामान्य में गिना गया', 'Кухня → Себестоимость'),
('cost_w_ov_unalloc', 'Расход периода, в котором нет вкушающих: не распределён', 'An expense for a period with no diners: not allocated', 'ऐसी अवधि का खर्च जिसमें भोजन करने वाले नहीं: वितरित नहीं', 'Кухня → Себестоимость'),
('cost_w_ov_unassigned', 'Расходы «на ретрит» без ретрита и назначения считаются общими, назначьте их ниже', 'Per-retreat expenses with no retreat or assignment are counted as general; assign them below', 'बिना रिट्रीट या नियुक्ति के रिट्रीट खर्च सामान्य गिने जाते हैं, उन्हें नीचे नियुक्त करें', 'Кухня → Себестоимость'),
('cost_w_labor', 'Выплата по статье «Зарплата» не связана с ведомостью: возможен двойной счёт с начислениями', 'A payment under "Salary" is not linked to the payroll: possible double counting with accruals', '"वेतन" मद का भुगतान वेतन-पत्रक से जुड़ा नहीं है: प्रोद्भवन के साथ दोहरी गिनती संभव', 'Кухня → Себестоимость'),
('cost_w_foreign', 'Зарплата не в рупиях, не учтена', 'Salary not in rupees, not counted', 'वेतन रुपये में नहीं है, गिना नहीं गया', 'Кухня → Себестоимость')
on conflict (key) do update set ru = excluded.ru, en = excluded.en, hi = excluded.hi, context = excluded.context;
